"""Local install layout and state helpers."""
from __future__ import annotations

import json
import os
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, cast


INSTALL_MARKER = ".vocalize-install-root"
INSTALL_STATE_FILE = "install.json"
PREFERENCES_FILE = "preferences.json"
PID_FILE = "vocalize.pid"
PROVIDERS_FILE = "providers.yaml"
ENV_FILE = ".env"
DEFAULT_INSTALL_DIRNAME = "VocalizeAI"
DEFAULT_PROVIDER_URL = "http://127.0.0.1:8765"


@dataclass(frozen=True)
class InstallPaths:
    root: Path

    @property
    def bin_dir(self) -> Path:
        return self.root / "bin"

    @property
    def app_dir(self) -> Path:
        return self.root / "app"

    @property
    def config_dir(self) -> Path:
        return self.root / "config"

    @property
    def logs_dir(self) -> Path:
        return self.root / "logs"

    @property
    def cache_dir(self) -> Path:
        return self.root / "cache"

    @property
    def env_file(self) -> Path:
        return self.config_dir / ENV_FILE

    @property
    def providers_file(self) -> Path:
        return self.config_dir / PROVIDERS_FILE

    @property
    def preferences_file(self) -> Path:
        return self.config_dir / PREFERENCES_FILE

    @property
    def install_state_file(self) -> Path:
        return self.config_dir / INSTALL_STATE_FILE

    @property
    def pid_file(self) -> Path:
        return self.cache_dir / PID_FILE

    @property
    def marker_file(self) -> Path:
        return self.root / INSTALL_MARKER

    @property
    def log_file(self) -> Path:
        return self.logs_dir / "vocalize.log"

    @property
    def local_cli(self) -> Path:
        return self.root / "vocalize"


def default_install_root(base_dir: Path | None = None) -> Path:
    """Return the default install root under the current folder."""
    return (base_dir or Path.cwd()) / DEFAULT_INSTALL_DIRNAME


def detect_install_root() -> Path:
    """Infer install root from env, packaged layout, or current directory."""
    raw = os.getenv("VOCALIZE_INSTALL_ROOT")
    if raw:
        return Path(raw).expanduser().resolve()

    executable = Path(sys.executable).resolve()
    for parent in [executable.parent, *executable.parents]:
        if (parent / "manifest.json").is_file() and (parent / "VERSION").is_file():
            return parent
        if (parent / INSTALL_MARKER).is_file():
            return parent
    return Path.cwd().resolve()


def ensure_install_dirs(root: Path) -> InstallPaths:
    """Create the self-contained install directories."""
    paths = InstallPaths(root.resolve())
    for directory in (
        paths.bin_dir,
        paths.app_dir,
        paths.config_dir,
        paths.logs_dir,
        paths.cache_dir,
    ):
        directory.mkdir(parents=True, exist_ok=True)
    return paths


def mark_install_root(root: Path) -> None:
    """Write the guard marker that makes uninstall safe."""
    paths = ensure_install_dirs(root)
    paths.marker_file.write_text("VocalizeAI local install\n", encoding="utf-8")


def has_install_marker(root: Path) -> bool:
    return (root / INSTALL_MARKER).is_file()


def write_env_file(
    paths: InstallPaths,
    *,
    openai_api_key: str,
    openai_base_url: str,
    openai_model: str,
    openai_thinking_mode: str,
    vocalize_port: int,
) -> None:
    """Write generated runtime env for ordinary local installs."""
    content = "\n".join(
        [
            "# Generated by `vocalize setup`.",
            "VOCALIZE_HOST=127.0.0.1",
            f"VOCALIZE_PORT={vocalize_port}",
            "VOCALIZE_STT_PROVIDER_URL=http://127.0.0.1:8765",
            "VOCALIZE_TTS_PROVIDER_URL=http://127.0.0.1:8765",
            "VOCALIZE_PROVIDER_CONNECT_TIMEOUT_S=5.0",
            "VOCALIZE_SPEECH_PROVIDER_AUTO_START=1",
            f"VOCALIZE_SPEECH_PROVIDER_COMMAND={paths.bin_dir / 'vocalize-mac-speech-provider'}",
            "VOCALIZE_SPEECH_PROVIDER_STARTUP_TIMEOUT_S=5.0",
            f"OPENAI_BASE_URL={openai_base_url}",
            f"OPENAI_MODEL={openai_model}",
            f"OPENAI_THINKING_MODE={openai_thinking_mode}",
            f"OPENAI_API_KEY={openai_api_key}",
            "DEFAULT_LANGUAGE=zh",
            f"LOG_DIR={paths.logs_dir}",
            "",
        ]
    )
    paths.config_dir.mkdir(parents=True, exist_ok=True)
    paths.env_file.write_text(content, encoding="utf-8")


def write_providers_yaml(paths: InstallPaths) -> None:
    """Write default macOS Provider API configuration."""
    content = "\n".join(
        [
            "version: 1",
            "stt:",
            "  provider: macos-native",
            f"  base_url: {DEFAULT_PROVIDER_URL}",
            "  input_encoding: pcm_s16le",
            "  input_sample_rate: 16000",
            "tts:",
            "  provider: macos-native",
            f"  base_url: {DEFAULT_PROVIDER_URL}",
            "  output_encoding: pcm_s16le",
            "  output_sample_rate: 24000",
            "",
        ]
    )
    paths.config_dir.mkdir(parents=True, exist_ok=True)
    paths.providers_file.write_text(content, encoding="utf-8")


def read_preferences(paths: InstallPaths) -> dict[str, object]:
    if not paths.preferences_file.is_file():
        return {}
    data = json.loads(paths.preferences_file.read_text(encoding="utf-8"))
    return cast(dict[str, Any], data)


def write_preferences(paths: InstallPaths, preferences: dict[str, object]) -> None:
    paths.config_dir.mkdir(parents=True, exist_ok=True)
    paths.preferences_file.write_text(
        json.dumps(preferences, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def read_install_state(paths: InstallPaths) -> dict[str, object]:
    if not paths.install_state_file.is_file():
        return {}
    data = json.loads(paths.install_state_file.read_text(encoding="utf-8"))
    return cast(dict[str, Any], data)


def write_install_state(paths: InstallPaths, state: dict[str, object]) -> None:
    paths.config_dir.mkdir(parents=True, exist_ok=True)
    paths.install_state_file.write_text(
        json.dumps(state, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def record_global_symlink(paths: InstallPaths, symlink_path: Path | None) -> None:
    state = read_install_state(paths)
    state["global_symlink"] = str(symlink_path) if symlink_path is not None else None
    write_install_state(paths, state)


def remove_recorded_global_symlink(paths: InstallPaths) -> None:
    state = read_install_state(paths)
    raw = state.get("global_symlink")
    if not isinstance(raw, str) or not raw:
        return
    symlink = Path(raw)
    if symlink.is_symlink() and symlink.resolve() == paths.local_cli.resolve():
        symlink.unlink()
    state["global_symlink"] = None
    write_install_state(paths, state)


def remove_install_root(paths: InstallPaths) -> None:
    """Remove the install root after marker validation."""
    if not paths.marker_file.is_file():
        raise RuntimeError(f"refusing to remove unmarked install root: {paths.root}")
    remove_recorded_global_symlink(paths)
    shutil.rmtree(paths.root)
